### ISSUE TITLE
bug in dht

### ISSUE THREAD

**Issue by proff** [mono/monotorrent#10]
mscorlib : System.IndexOutOfRangeException
Индекс находился вне границ массива.
   в System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   в System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   в MonoTorrent.Dht.Messages.MessageFactory.RegisterSend(QueryMessage message) в ....\MonoTorrent.Dht\MessageFactory.cs:строка 72
   в MonoTorrent.Dht.MessageLoop.EnqueueSend(Message message, IPEndPoint endpoint) в ...\MonoTorrent.Dht\MessageLoop.cs:строка 243
   в MonoTorrent.Dht.MessageLoop.EnqueueSend(Message message, Node node) в ...\MonoTorrent.Dht\MessageLoop.cs:строка 248
   в MonoTorrent.Dht.Tasks.SendQueryTask.Execute() в ...\MonoTorrent.Dht\Tasks\SendMessageTask.cs:строка 55
   в MonoTorrent.Dht.Tasks.GetPeersTask.SendGetPeers(Node n) в ...\MonoTorrent.Dht\Tasks\GetPeersTask.cs:строка 60
   в MonoTorrent.Dht.Tasks.GetPeersTask.<Execute>b__0() в ...\MonoTorrent.Dht\Tasks\GetPeersTask.cs:строка 46
   в MonoTorrent.Client.MainLoop.DelegateTask.Execute() в ...\MonoTorrent\MonoTorrent.Client\MainLoop.cs:строка 132
   в MonoTorrent.Client.MainLoop.Loop() в ...\MonoTorrent\MonoTorrent.Client\MainLoop.cs:строка 161

**Comment by alanmcgovern** [comment]
Maybe it's ok now?
