### ISSUE TITLE
how to create a .torrent file?

### ISSUE THREAD

**Issue by yuantantan** [mono/monotorrent#106]
I have a  mp4 file ,but I don't know how to convert it to .torrent file.Who can help me?

**Comment by alanmcgovern** [comment]
Use `TorrentCreator`. Add trackers, make it private, add a comment, etc.

https://github.com/mono/monotorrent/blob/master/src/MonoTorrent.Tests/Common/TorrentCreatorTests.cs#L117-L131

That shows how to add files to the torrent, and the rest of the tests show how to set other information. Hope that helps!

**Comment by alanmcgovern** [comment]
I did update the CreateAsync methods to be a more standard async pattern with CancellationToken support, and I added a few overloads.

The core logic is unchanged so my previous advise should still be accurate!

**Comment by yuantantan** [comment]
> Use `TorrentCreator`. Add trackers, make it private, add a comment, etc.
> 
> https://github.com/mono/monotorrent/blob/master/src/MonoTorrent.Tests/Common/TorrentCreatorTests.cs#L117-L131
> 
> That shows how to add files to the torrent, and the rest of the tests show how to set other information. Hope that helps!

It did solve my problem. Thank you very much.

**Comment by Marco-John535** [comment]
> > Use `TorrentCreator`. Add trackers, make it private, add a comment, etc.
> > https://github.com/mono/monotorrent/blob/master/src/MonoTorrent.Tests/Common/TorrentCreatorTests.cs#L117-L131
> > That shows how to add files to the torrent, and the rest of the tests show how to set other information. Hope that helps!
> 
> It did solve my problem. Thank you very much.

Hello, I am very interested in this project.
I want to create torrent file from source.
My code are as below.
******************************************************************************************************
            ITorrentFileSource fileSource = new TorrentFileSource(path);
            torrentCreator.CreateAsync(fileSource, "d:\\b"+ fileSource.TorrentName + ".torrent");
******************************************************************************************************
The torrent file is created but it does not seeding.
Please help me.
Thank you very much.

**Comment by alanmcgovern** [comment]
If you don't add any trackers to the torrent then you'll be relying on the Dht network for peers to locate each other. This can be slow, and you do have to make sure you enable Dht in MonoTorrent too. The sample client shows how this can be done!

The best option is to add a tracker to your torrent as it will be faster.

**Comment by Marco-John535** [comment]
> If you don't add any trackers to the torrent then you'll be relying on the Dht network for peers to locate each other. This can be slow, and you do have to make sure you enable Dht in MonoTorrent too. The sample client shows how this can be done!
> 
> The best option is to add a tracker to your torrent as it will be faster.

 @alanmcgovern ,Thank you very much. 
I construct public torrent tracker server (https://github.com/webtorrent/bittorrent-tracker)  and added this to my code.
Here is my code.
```
public async void CreateAndLoadTorrent(string path)
        {
            ClientEngine engine = new ClientEngine(new EngineSettings());

            TorrentCreator creator = new TorrentCreator();
            creator.Announces.Add(new RawTrackerTier(new[] { "http://192.168.5.151:8000/announce", "udp://192.168.5.151:8000"}));
            ITorrentFileSource files = new TorrentFileSource(path);

            BEncodedDictionary dict = await creator.CreateAsync(files);
            Torrent torrent = Torrent.Load(dict);


            BitField bitfield = new BitField(torrent.Pieces.Count).Not();
            FastResume fastResumeData = new FastResume(torrent.InfoHash, bitfield);

            TorrentManager manager = new TorrentManager(torrent, downloadPath, new TorrentSettings());
            manager.LoadFastResume(fastResumeData);

            engine.Register(manager);
            engine.StartAll();

            //MagnetLink magnet = new MagnetLink(manager.Torrent.InfoHash, manager.Torrent.Name, new[] { "http://192.168.5.151:8000/announce", "udp://192.168.5.151:8000" });
        }
```

But still does not seeding.
I tried use uTorrent program and made a torrent file from same file.
Input this torrent file to my code, I could download.
I found infoHash made by my code is different with uTorrent's.
Can you help me tell the reaon why this happens?
Best regards.

**Comment by alanmcgovern** [comment]
Can you file a new issue with this information and we'll diagnose it there. I don't want to spam the original reporter with unrelated issues :)

Thanks!

**Comment by Marco-John535** [comment]
> Can you file a new issue with this information and we'll diagnose it there. I don't want to spam the original reporter with unrelated issues :)
> 
> Thanks!

Ok. I issued in #272. Thank you.
