### ISSUE TITLE
you should compare peers by host and port

### ISSUE THREAD

**Issue by proff** [mono/monotorrent#11]
you should compare peers without peerId by host and port
possible scenarios:
1. two or more torrent clients on one computer (for example: test environment)
2. two or more clients in local network (external to our client) with NAT and port mapping or UPnP
3. torrent client changed port, we got endpoints with old port and new port. If we add enpoint with old port first, then we don't add endpoint with new port and couldn't connect to peer

**Comment by alanmcgovern** [comment]
It does!
```
        public bool Equals(Peer other)
        {
            if (other == null)
                return false;

            if (string.IsNullOrEmpty(peerId) || string.IsNullOrEmpty(other.peerId))
                return this.connectionUri.Host.Equals(other.connectionUri.Host);

            return peerId == other.peerId;
        }
```
