### ISSUE TITLE
Torrent not loading

### ISSUE THREAD

**Issue by Crazyx001** [mono/monotorrent#111]
Please help, why SampleClient can not download my torrent file, what could be the reason?

**Comment by alanmcgovern** [comment]
If you have a recent build then it was probably https://github.com/mono/monotorrent/commit/b777dcb229f8e1ee424742cfe42ffedefb5c5206

**Comment by alanmcgovern** [comment]
If the latest revision resolves the problem you were having (the regression from a few commits ago) then please close the issue. Otherwise do share as much information as you can to help me figure out what's going wrong. Thanks

**Comment by alanmcgovern** [comment]
If you're still getting issue that are not resolved by using a newer build, please reopen this. Based on the timing of your report the problem is most likely the short-lived regression which was addressed already. Thanks !

**Comment by Crazyx001** [comment]
Hello. Sorry for such a long answer, because I was away on business. Unfortunately your advice didn’t help me and yes, I am using the latest library build.
