### ISSUE TITLE
Sample download problem

### ISSUE THREAD

**Issue by skelder** [mono/monotorrent#115]
Hello,

I tried out the SampleClient with torrent for ubuntu distro iso

It seems that it can get list of peers but it cannot start the download.
the status is stuck at downloading with no outgoing or incoming connections
and some times the console screen just goes black showing nothing. 

I tried with other torrent client and it downloaded just fine.

Also is there any API guide or documentation? 

[ubuntu-18.04.3-desktop-amd64.iso.torrent.zip](https://github.com/mono/monotorrent/files/3529049/ubuntu-18.04.3-desktop-amd64.iso.torrent.zip)

**Comment by alanmcgovern** [comment]
That torrent downloads just fine on my side. 
<img width="1550" alt="Screenshot 2019-08-22 at 10 22 27" src="https://user-images.githubusercontent.com/264396/63503154-dd7c7280-c4c6-11e9-909c-9bd83e12e004.png">

If you are using an IDE to compile and run the sample client, could you pause the application in the debugger when it's stuck, then share a copy of the stacktrace of each thread? While unlikely, it's possible there's a deadlock somewhere and if you shared a copy of the stacktraces it would help me diagnose the issue.

For documentation, there's some on the old website ( https://smuxi.im/wiki/monotorrent ) but it needs to be updated after the recent migration to async/await, and also copied to the wiki in github.

**Comment by OneFingerCodingWarrior** [comment]
torrent works with me， everything just fine

**Comment by skelder** [comment]
While trying to get the call stack for the all the threads i noticed that System.Net.Sockets.SocketException was being thrown over and over again 

at line 71,

`await NetworkIO.ReceiveAsync (connection, messageLengthBuffer, 0, messageLength, rateLimiter, monitor?.ProtocolDown, manager?.Monitor.ProtocolDown).ConfigureAwait (false);`

at line 132

`transferred = await connection.ReceiveAsync(buffer, offset, remaining).ConfigureAwait(false); ;`

at line 277

`var message = await PeerIO.ReceiveMessageAsync(connection, decryptor, downloadLimiter, monitor, torrentManager);`

I took some screenshots of thread call stacks when the exceptions were thrown
![image](https://user-images.githubusercontent.com/10125862/63537149-0f85e700-c550-11e9-9857-250301638cfb.png)

![image](https://user-images.githubusercontent.com/10125862/63537458-bf5b5480-c550-11e9-89c0-c32ba402baf8.png)

![image](https://user-images.githubusercontent.com/10125862/63537546-f6316a80-c550-11e9-921a-f10739c80ddd.png)

The message that came with the Exception was
`"An existing connection was forcibly closed by the remote host"`

I think I am missing something trivial here.
I believe I configured the firewall correctly by allowing the ports both in and out.

Is there some set up procedure that I have to go through to properly use the library?

What I am doing right now is just clone the repository and then use Visual Studio 2019 to build the whole solution file.

**Comment by alanmcgovern** [comment]
Those exceptions are probably normal. If MonoTorrent decides to close a connection, or the remote peer closes it, it will manifest as a SocketException of some kind. The screenshots also don't show something that looks like a deadlock, which is good!

There are a few things we can try:

1) Are you on an IPV4 or IPV6 connection? If you're on IPV6, could you swap to IPV4 (tether to a mobile phone 4G connection?) and see if that makes a difference?

2) Attach to the `TorrentManager.PeerConnected` and `TorrentManager.PeerDisconnected` events and log the `PeerId.Uri` property along with the current time. This should tell us how many successful connections there were, and how long each connection was alive for. The connected event is raised *after* the initial handshake has completed. This means that encryption should have been negotiated and the BitTorrent [HandshakeMessage](https://github.com/mono/monotorrent/blob/master/src/MonoTorrent/MonoTorrent.Client.Messages/HandshakeMessage.cs) should have been sent/received successfully by both peers. [0]

3) If you see that new connections are being unexpectedly closed then you could try adding logging statements to two place:

*  [PeerIO.SendMessageAsync](https://github.com/mono/monotorrent/blob/master/src/MonoTorrent/MonoTorrent.Client/PeerIO.cs#L110). Here you should log `connection.Uri` and `msg.GetType().Name`.
* [PeerIO.ReceiveMessageAsync](https://github.com/mono/monotorrent/blob/master/src/MonoTorrent/MonoTorrent.Client/PeerIO.cs#L94). Here you should log `connection.Uri` and `data.GetType().Name`

This will tell us which messages are being sent/received by each peer, and from that we may notice a pattern.

4) Temporarily disable the firewall and see if that helps. It's highly unlikely the firewall is affecting things though.

[0] I think it could be beneficial to tweak the semantics of this event and only raise it after the *second* message has been received, which will be a [HaveAll](https://github.com/mono/monotorrent/blob/master/src/MonoTorrent/MonoTorrent.Client.Messages.FastPeer/HaveAllMessage.cs), [HaveNone](https://github.com/mono/monotorrent/blob/master/src/MonoTorrent/MonoTorrent.Client.Messages.FastPeer/HaveNoneMessage.cs) or [BitfieldMessage](https://github.com/mono/monotorrent/blob/master/src/MonoTorrent/MonoTorrent.Client.Messages/BitfieldMessage.cs). This means the remote peer will have received the HandshakeMessage from MonoTorrent and considered it valid/acceptable. This is the strongest guarantee that things have connected correctly.

**Comment by skelder** [comment]
```
'SampleClient.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SampleClient.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'D:\Software Installation exe\monotorrent\src\SampleClient\bin\Debug\net472\SampleClient.exe'. Symbols loaded.
'SampleClient.exe' (CLR v4.0.30319: SampleClient.exe): Loaded 'D:\Software Installation exe\monotorrent\src\SampleClient\bin\Debug\net472\MonoTorrent.dll'. Symbols loaded.
'SampleClient.exe' (CLR v4.0.30319: SampleClient.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\netstandard\v4.0_2.0.0.0__cc7b13ffcd2ddd51\netstandard.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SampleClient.exe' (CLR v4.0.30319: SampleClient.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SampleClient.exe' (CLR v4.0.30319: SampleClient.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SampleClient.exe' (CLR v4.0.30319: SampleClient.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SampleClient.exe' (CLR v4.0.30319: SampleClient.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'SampleClient.exe' (CLR v4.0.30319: SampleClient.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ValueTuple\v4.0_4.0.0.0__cc7b13ffcd2ddd51\System.ValueTuple.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.

SendMeesageAsync
ipv4://192.168.245.33:6969/
HandshakeMessage

SendMeesageAsync
ipv4://192.168.245.33:61786/
HandshakeMessage

PeerConnected
ipv4://192.168.245.33:6969/
2:47:00 PM

SendMeesageAsync
ipv4://192.168.245.33:6969/
MessageBundle

RecieveMeesageAsync
ipv4://192.168.245.33:6969/

PeerDisconnected
ipv4://192.168.245.33:61786/
2:47:00 PM
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll

PeerDisconnected
ipv4://192.168.245.33:6969/
2:47:00 PM

SendMeesageAsync
ipv4://174.96.212.4:61690/
HandshakeMessage
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in MonoTorrent.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll

PeerDisconnected
ipv4://174.96.212.4:61690/
2:47:02 PM

SendMeesageAsync
ipv4://91.189.95.21:6944/
HandshakeMessage
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in MonoTorrent.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll

PeerDisconnected
ipv4://91.189.95.21:6944/
2:47:02 PM

SendMeesageAsync
ipv4://174.86.140.185:51413/
HandshakeMessage
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in MonoTorrent.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll

PeerDisconnected
ipv4://174.86.140.185:51413/
2:47:02 PM
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll

SendMeesageAsync
ipv4://185.65.134.160:18849/
HandshakeMessage
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in MonoTorrent.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll

PeerDisconnected
ipv4://185.65.134.160:18849/
2:47:03 PM
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll

SendMeesageAsync
ipv4://134.249.136.112:29905/
HandshakeMessage
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in MonoTorrent.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll

PeerDisconnected
ipv4://134.249.136.112:29905/
2:47:04 PM
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll

SendMeesageAsync
ipv4://188.93.111.3:51413/
HandshakeMessage
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in MonoTorrent.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll

PeerDisconnected
ipv4://188.93.111.3:51413/
2:47:06 PM
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll

SendMeesageAsync
ipv4://213.152.161.25:49244/
HandshakeMessage
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in MonoTorrent.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll

PeerDisconnected
ipv4://213.152.161.25:49244/
2:47:06 PM

SendMeesageAsync
ipv4://46.188.102.37:51413/
HandshakeMessage
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in MonoTorrent.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll

PeerDisconnected
ipv4://46.188.102.37:51413/
2:47:06 PM
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll

SendMeesageAsync
ipv4://90.89.144.85:49717/
HandshakeMessage
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll

SendMeesageAsync
ipv4://109.91.115.192:24781/
HandshakeMessage
Exception thrown: 'System.Exception' in MonoTorrent.dll
Exception thrown: 'System.Exception' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in MonoTorrent.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll

PeerDisconnected
ipv4://90.89.144.85:49717/
2:47:09 PM
Exception thrown: 'System.Exception' in mscorlib.dll
Exception thrown: 'System.Exception' in MonoTorrent.dll
Exception thrown: 'System.Exception' in mscorlib.dll

PeerDisconnected
ipv4://109.91.115.192:24781/
2:47:09 PM
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll

SendMeesageAsync
ipv4://209.141.54.248:56405/
HandshakeMessage
Exception thrown: 'System.Exception' in MonoTorrent.dll
Exception thrown: 'System.Exception' in mscorlib.dll
Exception thrown: 'System.Exception' in mscorlib.dll
Exception thrown: 'System.Exception' in MonoTorrent.dll
Exception thrown: 'System.Exception' in mscorlib.dll

PeerDisconnected
ipv4://209.141.54.248:56405/
2:47:12 PM
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll

SendMeesageAsync
ipv4://188.156.115.140:6881/
HandshakeMessage
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in MonoTorrent.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll

PeerDisconnected
ipv4://188.156.115.140:6881/
2:47:13 PM
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
The thread 0x47e0 has exited with code 0 (0x0).
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in mscorlib.dll
The thread 0x7c70 has exited with code 0 (0x0).
The thread 0x5e14 has exited with code 0 (0x0).
The thread 0x7814 has exited with code 0 (0x0).
The thread 0x5490 has exited with code 0 (0x0).
The program '[36964] SampleClient.exe' has exited with code -1073741510 (0xc000013a).
```

So this is the Debug output after adding `Debug.WriteLine` to the mentioned methods.

I only saw `PeerConnected` from the very first peer which then immediately disconnects.

After that pattern is pretty much same with `SendMessageAsync` sending the `HandshakeMessage` then the `PeerDiconnected` being called on the same peer immediately

I think `RecieveMessageAsync` has some problems because it cannot reach the point where `data` is available to see what kind of message we received.

[1] I am currently using ipv4

[4] and I tried turning off the firewall and it seems to have no effect on the problem.

**Comment by alanmcgovern** [comment]
It really does look like every connection is being closed as soon as the handshake is sent, which is odd. Can you tell if MonoTorrent is terminating the connection, or if the remote peer is terminating it? I assume the remote peer is terminating it, but it may be hard to tell for sure. I think one way to check would be to put a logging statement in both `IPV4Connection.Dispose` and `ConnectionManager.CleanupSocket` and making sure these are invoked *after* a SocketException has been thrown by either `IPV4Connection.SendAsync` or `IPV4Connection.ReceiveAsync`.

More importantly, can you try three variations in encryption settings for me and see if any make a difference:
1) `ClientEngine.Settings.AllowedEncryption = EncryptionTypes.RC4Full`
2) `ClientEngine.Settings.AllowedEncryption = EncryptionTypes.RC4Header`
3) `ClientEngine.Settings.AllowedEncryption = EncryptionTypes.PlainText`

The first option should, hopefully, rule out any form of packet inspection software closing connections as soon as it sees the plain text `BitTorrent protocol` string sent in the first few bytes . by ensuring only fully encrypted connections are used.

**Comment by skelder** [comment]
Good news it works when `AllowedEncryption` is set to `RC4Full` or `RC4Header`. `Plaintext` did not work. 

Also i added the Debug line to `ConnectionManager.CleanupSocket` and it was being called after the exception were being thrown.

I could not find the `IPv4Connection.Dispose` in the code(maybe i am blind) so i could not add the debug line there.

But yeah I guess I will just enforce the `RC4Full` encryption in my applications?
Is there any possible downside of enforcing only this type of encryption??

**Comment by alanmcgovern** [comment]
> Good news it works when AllowedEncryption is set to RC4Full or RC4Header. Plaintext did not work.

I am 99% certain that you are witnessing your ISP running a traffic inspector which closes bittorrent related connections. Forcing encryption (of any sort) bypasses this by scrambling the first few bytes. As such, a second way to work around your problem would be:

```
EngineSettings.AllowedEncryption = EncryptionTypes.All;
EngineSettings.PreferEncryption = true;
```

[This means encrypted connections will be tried first, then if that fails it will remove encrypted connections from the allowed set and try plaintext.](https://github.com/mono/monotorrent/blob/d8c14ca865b457243840fb18fddb45a3f435bf0d/src/MonoTorrent/MonoTorrent.Client/Managers/ConnectionManager.cs#L264-L269)

However, it does point to an issue. The outgoing connection fallback logic only goes from strong encryption to weak encryption when a failure occurs. i.e. if RC4Full or RC4Header fails, it will fall back and try PlainText. The issue you're having is that you're starting with PlainText and failing, then it's trying PlainText again. I have [tweaked the logic](https://github.com/mono/monotorrent/blob/9e1de8c4fb29709edc7189bc0be9cfa3ab151951/src/MonoTorrent/MonoTorrent.Client/Managers/ConnectionManager.cs#L217-L232) to address this. If you're feeling adventurous, feel free to check out the work-in-progress [cleanup-peerid](https://github.com/mono/monotorrent/tree/cleanup-peerid) branch and see if it establishes connections without having to mess around with any EngineSettings. It should try plaintext first, and then when that fails it will try Encryption.

> I could not find the IPv4Connection.Dispose in the code(maybe i am blind) so i could not add the debug line there.

Ah yes, `IPV4Connection` inherits from `SocketConnection` and that's where the Dispose method is. I don't think we need to do any further checks now though, I think it's a pretty clear ISP issue since Encryption fixes it!

> But yeah I guess I will just enforce the RC4Full encryption in my applications? Is there any possible downside of enforcing only this type of encryption??

The downsides are that any client (or peer) which does not support, or has disabled, encryption won't be able to connect. It also consumes a little bit more CPU, but I don't think CPU usage is going to be an issue for any computer bought within the last decade.

In order of preference what I'd recommend would be:
1) When my branch fixing the fallback to allow it to go from PlainText -> Encrypted lands then your problem *should* go away. The engine will always try Encrypted and Unencrypted connections.
2) Change the `EngineSettings.PreferEncryption` property to `true` and everything will still be supported, but RC4Full encryption will be preferred when making outgoing connections.
3) I add a slightly better fallback mechanism so you can select RC4Header as the preferred default for outgoing connections, then RC4Full, then PlainText. RC4Header would give you encrypted handshakes with no further performance penalty when the connection is running.
4) Just enable RC4Full as the only option and assume that all modern bittorrent clients support this 10+ year old feature and that minor increase in CPU usage is fine (which it is!).

Thinking about how old the feature is, option 4 is kinda compelling :p

**Comment by skelder** [comment]
Awesome, thank you for the great support.

We are planning to use monotorrent inside Unity3D application for some in-app asset sharing which means that we do not really care about other clients out there, so I think we are golden for now.

Now that I know there are basically no downside to use the encryption I will just go for the option 4

Again thanks a lot and keep up the awesome work.

**Comment by alanmcgovern** [comment]
Great stuff. Glad that was easy enough to sort out! Let me know if you have any other issues.

I'm attempting to regain control of the `MonoTorrent` nuget package so I can ship updates on nuget.org. But in the meantime do grab releases from  [here](https://github.com/mono/monotorrent/releases) or just compile it yourself. I'm redoing chunks of API (moving to async/await was a big break so i took the opportunity to change other things) so it'll be a little unstable for the next few weeks, but i think the majority of the work is probably done now.
