### ISSUE TITLE
Private field

### ISSUE THREAD

**Issue by justscribe** [mono/monotorrent#128]
Hi,

Why you don't set it to public, how can I retrieve all torrents from TrackerServer?
Thank you.
https://github.com/mono/monotorrent/blob/25d31275b872a097541456df7f7ef99b8b29ca37/src/MonoTorrent/MonoTorrent.Tracker/TrackerServer.cs#L123

**Comment by alanmcgovern** [comment]
Every usage of that field internally is protected by a lock for thread safety.

You can [Register](https://github.com/mono/monotorrent/blob/master/src/MonoTorrent/MonoTorrent.Tracker/TrackerServer.cs#L356-L365) as many `ITrackerListener` instances as you wish with the `TrackerServer` object. At any point in time one, or more, of those may receive a request and will attempt to [access](https://github.com/mono/monotorrent/blob/master/src/MonoTorrent/MonoTorrent.Tracker/TrackerServer.cs#L244-L271) the `Torrents` dictionary. This may add additional elements to the dictionary, mutating it.

If anyone has direct access to that dictionary and is iterating using a `foreach` loop, or is trying to mutate it themselves, or even simply doing a lookup for an item, it can throw exceptions or corrupt state if a request is processed at the same time.

I'm pretty sure everything else would be threadsafe (but i should double check), but I think you can implement this safely by doing something like:

```
public List<SimpleTorrentManager> GetTorrents ()
{
    lock (Torrents)
        return new List<SimpleTorrentManager> (Torrents.Values);
}
```

I've been eyeing up this API for a while to do a bit of a cleanup on it. Is there anything else you feel you would need access to? The main change I have in mind is to make `SimpleTorrentManager` an internal class and expose it through an interface instead, perhaps something like:

```
    interface ITrackerItem
    {
        /// <summary>
        /// The number of active seeders
        /// </summary>
        long Complete { get; }

        /// <summary>
        /// The total number of peers being tracked
        /// </summary>
        long Count { get; }

        /// <summary>
        /// The total number of times the torrent has been fully downloaded
        /// </summary>
        long Downloaded { get; }

        /// <summary>
        /// The number of active leechers
        /// </summary>
        long Incomplete { get; }
        ITrackable Trackable { get; }

        /// <summary>
        /// Return a copy of the list of peers
        /// </summary>
        /// <returns></returns>
        List<Peer> GetPeers();
    }
```
Would that fit your needS?

**Comment by justscribe** [comment]
Thanks, that implementation of getting torrent list is great. Maybe it should to be committed in the master brunch?
