### ISSUE TITLE
Is it possible to implement disabling Hash check for files with Priority.DoNotDownload?

### ISSUE THREAD

**Issue by justscribe** [mono/monotorrent#136]
Hi,

So, the question: is it possible to implement disabling Hash check for files with Priority.DoNotDownload?

**Comment by alanmcgovern** [comment]
It's definitely possible, and n
I don't think it would be too hard.

If those files start as do not download and are then set to "priority.normal" at runtime we'd have to hash check the file before allowing any pieces to be selected for downloading. We'd also send have messages to every peer we're connected to for each piece which was valid.

However, this is only beneficial if the hash check costs CPU time or HDD access time.  If FastResume data is stored for a torrent then the hash check will be free.

Would it be simpler for you to ensure fast resume data is always saved/restored? Under which circumstance would a partial hash of the torrent, as you described, be a better option than saving/restoring fast resume data? I can think of one or two, but they seem a bit niche :) I'm curious what yours is.

**Comment by justscribe** [comment]
The problem in changing Torrent for the same files, I've implemented my own quick hash check and want to download only files, that are not matched. From this point we're loosing fast resume, because the Torrent hashinfo has changed.

**Comment by alanmcgovern** [comment]
It sounds like your scenario is this:

There are multiple torrents referencing different subsets of the same files. You want to download all the files in Torrent A, then download Torrent B. When downloading Torrent B you will mark a lot of files as "DoNotDownload" at the start. You want these to not be hashed as you know they are on disk and you know the hash is good.

If so, there is one way of accomplish this. Create a FastResume object and manually set the bitfield to true/false. You could set the entire thing to true, and then iterate over all the fiels which do not exist and set the piece indices to "false" so they will download. You just have to be careful when handling pieces which contain multiple files. If any file is missing then the entire piece should be marked as false (missing).  

Would that work?

If not, I can investigate better internal support for this scenario :)

**Comment by justscribe** [comment]
If I understood you correctly, the implementation should be like:
1. Creating custom fast resume:
private FastResume GetFastResume(Torrent aTorrent) {
	return new FastResume(aTorrent.InfoHash, new BitField(aTorrent.PieceLength));
}
2. Loading fast resume:
public void LoadCustomFastResume(FastResume aFastResume, TorrentManager Torrent) {
	foreach (TorrentFile torrentFile in torrent.Torrent.Files) {
		if (torrentFile.Priority == Priority.DoNotDownload) {
			for (int i = torrentFile.StartPieceIndex; i < torrentFile.EndPieceIndex; i++) {
				aFastResume.Bitfield.Set(i, true);
			}
		} else {
			for (int i = torrentFile.StartPieceIndex; i < torrentFile.EndPieceIndex; i++) {
				aFastResume.Bitfield.Set(i, false);
			}
		}
	torrent.LoadFastResume(aFastResume);
	}		
}

Is it?

**Comment by justscribe** [comment]
Thank you for response.
I've tried that, but with no luck.
TorrentManager really skips hashing mode, but then it downloads the rest files very slowly, like it tries every time to get that "DoNotDownload" files, but can't. The download speed jumps, as less often as less files I want to download. I've also tried a combined way with custom FastResume, but the result even worst.

My implementation was:
public class DoNotDownloadWriter : DiskWriter
    {
        public DoNotDownloadWriter() {
        }

        public DoNotDownloadWriter(int maxOpenFiles) : base(maxOpenFiles) {
        }

        public override int Read(TorrentFile file, long offset, byte[] buffer, int bufferOffset, int count) {
            if (file.Priority == Priority.DoNotDownload) {
                return 0;
            }
            return base.Read(file, offset, buffer, bufferOffset, count);
        }

        public override bool Exists(TorrentFile file) {
            if (file.Priority == Priority.DoNotDownload) {
                return false;
            }
            return base.Exists(file);
        }

        public override void Write(TorrentFile file, long offset, byte[] buffer, int bufferOffset, int count) {
            if (file.Priority == Priority.DoNotDownload) {
                return;
            }
            base.Write(file, offset, buffer, bufferOffset, count);
        }

        public override void Flush(TorrentFile file) {
            if (file.Priority == Priority.DoNotDownload) {
                return;
            }
            base.Flush(file);
        }
    }

**Comment by catholic** [comment]
What PiecePicker chain are you using?
Is it something like?:
torrentManager.ChangePicker(new PriorityPicker(new StandardPicker()));

**Comment by justscribe** [comment]
I've tried like that and with no changing (it creates its own PriorityPicker by default).

**Comment by catholic** [comment]
> it creates its own PriorityPicker by default

Yes, in TorrentManager PriorityPicker is used as first PiecePicker by default.
That's why I'm asking you what combination of pickers are you using.

If default combination is used, then your assumption

> like it tries every time to get that "DoNotDownload" files, but can't.

is wrong

You need to provide more information if you need help.

You need to debug PickPiece() method in Picker to make sure when and what TorrentManager tries to do.

To make ClientEngine more nimble try to increase EngineSettings.MaximumHalfOpenConnections from 5 to 50 or something like that

**Comment by justscribe** [comment]
Is it ok that PickPiece startIndex and endIndex alsways the same, from 0 to MyValue?

**Comment by catholic** [comment]
Yes, this is correct.
Torrent files are immutable, so torrent file always have the same start and end indexes
This index range is not for current downloading file from torrent, but for all files from torrent

**Comment by alanmcgovern** [comment]
> There is nothing to check, I've deleted files that do not match the hash, so the torrent must to start download immediatly, but it still checks the hashes of files with "Priority.DoNotDownload".

Yeah, i realised afterwards that the torrent will attempt to hash any files which are on disk as long as at least *one* file is on disk.

My idea for implementing this feature is here: https://github.com/mono/monotorrent/tree/do-not-download . That branch is not complete, but it should give an idea of what it will accomplish in the end.

**Comment by justscribe** [comment]
Thank you, looks great. And that will be good tested, I promise)

**Comment by alanmcgovern** [comment]
I've added a few tests and fixed some issues with the draft. I think it's probably OK to test this out now. The limitation is that the priorities have to be set before you start the torrent for the first time, and you shouldn't change them afterwards.

I'll add the remaining logic to hash check files which change priority during download when I get the time.

**Comment by justscribe** [comment]
Tested on my project, the implementation works fine.
TorrentManager skips Hash check for files with "Priority.DoNotDownload" as expected.
One thing, overall progress provided by "TorrentManager.Progress" dont show the real progress according to files, that we dont want to download.
For example: we have 20Gb for all torrent, right now we're downloading only 5Gb from it, so when we will finish to download that 5Gb, the progress must to be 100%, but not a 25%. If I understood correclty, with this feature we're do not seeding the rest of files, that are with "Priority.DoNotDownload", so it makes sence to count the only files with differ priority.
Thank you a lot.

**Comment by catholic** [comment]
Each TorrentFile has TorrentFile.BitField.PercentComplete

You can summarize PercentComplete from each file that is not "DoNotDownload" and divide by count of them to get 0-100% progress

You can do this for example in event handler for TorrentManager.PieceHashed

**Comment by justscribe** [comment]
Ofc I can do that by myself, but it seems to me right, don't count files that didn't involved is seeding, downloading or else.

**Comment by catholic** [comment]
No, it's not right.

TorrentManager is created from a Torrent file. Torrent file has constant Size, that is a summary of all files included in Torrent. So, if we are getting the progress of Torrent by calling TorrentManager.Progress we must get a percent of what we have of Torrent. 

TorrentManager.Progress and Torrent Size must not depend on the individual behavior of files in Torrent

**Comment by justscribe** [comment]
Ok.
So in the end, the solution works fine.

**Comment by alanmcgovern** [comment]
I'm a little worried about changing the semantics of `TorrentManager.Progress`. The intended semantics are to represent the completion ratio for the *entire* torrent, and the value here is used in things like Announce requests.

It would be relatively easy to expose a second property `public double PartialSeedingProgress { get; }`, but the naming could be confusing. Does this seem worthwhile?

The name 'PartialSeedingProgress' is derived the [Partial Seeding BEP](http://www.bittorrent.org/beps/bep_0021.html) which covers how trackers can be informed that someone has deliberately chosen to only download a portion of the entire torrent. This BEP isn't implemented either as it did not seem super useful.

**Comment by alanmcgovern** [comment]
I landed the next set of changes, which allows you to dynamically change the priority from `DoNotDownload` -> `anything else` and have the files begin downloading.

**Comment by justscribe** [comment]
> I'm a little worried about changing the semantics of `TorrentManager.Progress`. The intended semantics are to represent the completion ratio for the _entire_ torrent, and the value here is used in things like Announce requests.
> 
> It would be relatively easy to expose a second property `public double PartialSeedingProgress { get; }`, but the naming could be confusing. Does this seem worthwhile?
> 
> The name 'PartialSeedingProgress' is derived the [Partial Seeding BEP](http://www.bittorrent.org/beps/bep_0021.html) which covers how trackers can be informed that someone has deliberately chosen to only download a portion of the entire torrent. This BEP isn't implemented either as it did not seem super useful.

I think It's not really necessary. If we're using the DoNotDownload priority, then we need to handle that situation and calculate a proper Progress by myself.

**Comment by alanmcgovern** [comment]
Ok, so i've been giving this a bit of testing today and it seems to be working great! Have you guys tried out this version of the patchset and does it work well for you?

**Comment by alanmcgovern** [comment]
For reference: https://github.com/mono/monotorrent/pull/141

**Comment by justscribe** [comment]
> Ok, so i've been giving this a bit of testing today and it seems to be working great! Have you guys tried out this version of the patchset and does it work well for you?

Hi,
Did the TorrentManager changed the mode to "Seeding" after all files downloaded with some of files with priority "DoNotDownload"? In my case it seeding files, but the mode didn't changed, is it possible?

**Comment by alanmcgovern** [comment]
The mode changes to 'Seeding' when Progress is 100%, and Progress is only 100% when all the files are downloaded. The state change does not affect anything as the underlying `Mode` object is `DownloadMode` regardless of whether you are Seeding or Downloading.

If I go ahead and put this stuff in the core library ( https://github.com/mono/monotorrent/issues/136#issuecomment-535917614 ) then making the status change to `Seeding` when the `PartialProgress` is 100% would definitely be possible.

**Comment by justscribe** [comment]
Yes, at this point I think it is a good idea to implement **PartialProgress** and refering to that set the correct mode.

**Comment by alanmcgovern** [comment]
This should add the additional behavioural changes, and the new property to track the partial progress.

https://github.com/mono/monotorrent/pull/147

**Comment by alanmcgovern** [comment]
https://github.com/mono/monotorrent/pull/147 has been merged so I'll close this again. If we need any further changes do let me know!
