### ISSUE TITLE
MaximumDownloadSpeed and MaximumUploadSpeed do not make any affect on Download and Upload speed limit

### ISSUE THREAD

**Issue by catholic** [mono/monotorrent#137]
It seems that ChokeUnchokeManager not working anymore as it should.
Download and upload processes are always at their maximum speed.

**Comment by alanmcgovern** [comment]
Are you setting `TorrentSettings.MaximumDownloadSpeed` or `EngineSettings.MaximumDownloadSpeed`?

**Comment by catholic** [comment]
I tried both options and they are not working

**Comment by alanmcgovern** [comment]
Actually there's probably still an issue with choking/unchoking. Historically that was contributed and I didn't have a thorough understanding of it, so if you can describe what the issue is I can look into it when I get around to redoing it properly

**Comment by catholic** [comment]
Right now limits are working.

But changing EngineSettings.MaximumDownloadSpeed or EngineSettings.MaximumUploadSpeed, after ClientEngine was started, doesn't have any effect.

It only takes into account settings that were set before ClientEngine was started. TorrentManager stop/start didn't help either

Changing limits dynamically during download process for TorrentSettings.MaximumDownloadSpeed and TorrentSettings.MaximumUploadSpeed works correctly

**Comment by alanmcgovern** [comment]
Should be fixed by https://github.com/mono/monotorrent/commit/f47dd95c4eafb0b48cc1c6f90a9714365b3aa7f1 . Thanks!

**Comment by catholic** [comment]
Yes, can confirm that fixed!
