### ISSUE TITLE
Autohandle file changes.

### ISSUE THREAD

**Issue by justscribe** [mono/monotorrent#145]
Hi,

Another idea for new feature.
Can we do not block files from changing (stream FileShare.ReadWrite), but if file was changed, set it priority to DoNotDownload?
Maybe with new file property, that tells about local changing (IsChangedLocally sets to true).
Then after hash recheck it returns to false.
I know that we can set handler to check the file operations inside the folder.
Maybe it must to be such a new mode of seeding that can be setted by TorrentSettings.

**Comment by alanmcgovern** [comment]
There are a few issues that would concern me about this:

1) Resource usage: If a large file is changed externally, the entire file would have to be re-hashed. If this happens with any frequency it would be pretty bad.

2) Accuracy: I don't think it is possible to disambiguate between a file-change notification triggered by a write from MonoTorrent or from an external program. The most likely result is that modifications from an external file will be treated as if they were MonoTorrent writes if they happen at the same time as a Write event from monotorrent, thus we would not realise the file has changed externally.

3) There's no 'UnHave' support. Once a handshake is sent, or a have message is sent, there's no way to mark yourself as *not* having a piece anymore. As such we could end up in a situation where we must reject piece requests even though we have claimed we have those pieces. This would probably be detrimental.

This use-case seems very application specific, so perhaps putting this logic in your application would be the best approach. The least efficient, but possibly best, way to implement this behaviour would probably be to call `await TorrentManager.StopAsync ()` and `await TorrentManager.HashCheckAsync(true)` every time the file changes externally. It's the best option to ensure all state is consistent. If the external changes are infrequent, then this may be performant enough.

If the external changes are frequent, then it'd be quite complicated to get a performant approach.

**Comment by alanmcgovern** [comment]
I'll close this because I don't think this will end up in the actual implementation. If you want any tips on optimising this feature in your impl, i.e. something better than `StopAsync ()` and `HashCheckAsync ()` just ask and I'll see what I can think of.
