### ISSUE TITLE
Plans for HTTP seeds?

### ISSUE THREAD

**Issue by samhocevar** [mono/monotorrent#149]
Hi, and thanks for your recent work on refactoring the library, the architecture seems a lot cleaner.

I was wondering whether you had plans to reinstate the HTTP seeds? The code in `Mode.DownloadLogic()` was commented out in d5b3423d617cf278e1c546368506650961ed4d70 and it doesn’t look straightforward to me how to port it to the new architecture.

**Comment by alanmcgovern** [comment]
Good point. I'll review that and get it re-enabled as soon as possible!

**Comment by alanmcgovern** [comment]
I just released 1.0.4 with the latest round of performance optimisations. The two changes that went in have made a drastic improvement so I figured it was worth releasing it sooner rather than later. I'll look into this next and issue a release once it's ready!

**Comment by alanmcgovern** [comment]
@samhocevar  Did you get a chance to test the PR just to see if the basics worked for you?

If they do, I'd love some feedback on how you intend to use the feature so I can tweak the heuristic which adds/removes HTTP peers to be better in  real world scenarios.

**Comment by samhocevar** [comment]
@alanmcgovern sorry, I haven’t been able to test it yet because the library now targets a very recent framework and I’m in the process of tweaking the rest of our codebase so that it can build properly.

Our use case is for an internal network only, so our heuristics would probably not be ideal for internet torrents. You can see [in this commit](https://github.com/dontnod/monotorrent/commit/02681929de6ea8df81c55a87625eb395da4e9578) that we made the constants configurable, I think this could be applied upstream once I can confirm that web seeds work again.

**Comment by alanmcgovern** [comment]
Oh, sorry for that! If you compile things from source then I did move to C# language version 8.0. This was mostly to gain the ability to write [Using statements](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#using-declarations)

The library itself will still be .NET 2.0 compatible and so if you reference the NuGet you won't have to make any changes to your compilation process. If it helps I could provide NuGet packages generated from that branch for testing purposes, so you don't have to compile it yourself.

**Comment by samhocevar** [comment]
I can confirm that webseeds work properly on our LAN.

FYI, we use MonoTorrent as part of our internal game deployment infrastructure. Torrents are created for each build and allow developers to quickly deploy binaries and debug symbols for a given commit. Sometimes bootstrapping a torrent takes time and webseeds help with the situation.

**Comment by alanmcgovern** [comment]
Perfect! I'll try to roll your configuration patch into the core, finish tweaking webseeds, and then we should be good to merge this!

**Comment by alanmcgovern** [comment]
I just merged the changes. I'll roll a new release later in the week, including this change, assuming the ReusableTask related issue is well and truly quashed :)

**Comment by alanmcgovern** [comment]
Fixed with https://github.com/mono/monotorrent/pull/152
