### ISSUE TITLE
Sending messages to the tracker

### ISSUE THREAD

**Issue by zFerz** [mono/monotorrent#18]
Monoterrent does not send messages to the tracker about status changes:

stopped: Must be sent to the tracker if the client is shutting down gracefully.
completed: Must be sent to the tracker when the download completes. However, must not be sent if the download was already 100% complete when the client started. Presumably, this is to allow the tracker to increment the "completed downloads" metric based solely on this event.

maybe, there are some others, but this is most important for me.
(http://wiki.theory.org/BitTorrentSpecification)

**Comment by alanmcgovern** [comment]
It does!
