### ISSUE TITLE
Not downloading torrent file

### ISSUE THREAD

**Issue by mathias234** [mono/monotorrent#184]
Hello, we have been trying to use this library to distribute patches for out client. But we have encountered a problem with one of our patches. 

It is stuck on State Downloading with 0% downloaded with 0kb/s download speed.
the torrent file works in bittorrent and deluge. 

we have currently tried three different torrents in our app all except this one is working.
Had to put in a zip file to be able to upload it here
[test.zip](https://github.com/mono/monotorrent/files/3854266/test.zip)

We are thinking this might be caused by the patch being so small.

**Comment by alanmcgovern** [comment]
Yup, the issue is the patch is so small it's making the engine go into 'EndGame' mode immediately, and in that scenario the Standard picker was never initialised, however the standard picker can still be invoked.
