### ISSUE TITLE
ReusableTasks dll not found.

### ISSUE THREAD

**Issue by justscribe** [mono/monotorrent#188]
Hi,

After the last commit the module is not working but builds succesfully.
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.IO.FileNotFoundException: Could not load file or assembly 'ReusableTasks, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

That's happening when I try to create a new instance of ClientEngine.
Thanks for help.

**Comment by alanmcgovern** [comment]
If you reference the nuget for monotorrent you should also get an implicit reference to ReusableTasks. 

Can you double check ReusableTasks.dll is being copied/deployed with your application?

**Comment by alanmcgovern** [comment]
On a side note, it looks like the sanity check is doing it's job and is forcing the error to surface quickly and reliably if the assembly is missing :) https://github.com/mono/monotorrent/commit/b3227b0237f9aae6e3397203d436d09f96ca1cda

**Comment by justscribe** [comment]
I've cloned monotorrent project from GIT. After I've added the package manually from nuget, the issue was solved.

**Comment by alanmcgovern** [comment]
If you are building from source and your application project is referencing MonoTorrent.csproj, then i would expect ReusableTasks.dll to be copied to the output directory of your executable project too. That's how it works with `SampleClient.csproj` in monotorrent's own repository.

If you're directly referencing the compiled MonoTorrent.dll binary from the build output directory then you'll have to manually reference the same (or newer) version of the ReusableTasks nuget to make sure it is copied correctly.

A direct reference to the ReusableTask nuget should solve any copy-to-output-directory issues too :)

Glad you have it (mostly) working now though!

**Comment by justscribe** [comment]
My project is referencing to MonoTorrent.csproj, but dll was not copied, even after many cleans/rebuilds.

**Comment by justscribe** [comment]
And there is no such dll inside MonoTorrent project bin directory.

**Comment by alanmcgovern** [comment]
It won't be copied to the output directory of MonoTorrent.csproj, but it will be copied to the output directoy of both MonoTorrent.Tests and SampleClient. It won't be copied to the output directory of DotNetCoreSample because .net core uses a different mechanism to find the ReusabletTasks binary in this scenario.

An explicit dependency on your executable project should solve the problem. The exact treatment of transitive local copies is highly dependent on a number of things, so it's kinda tricky to rely on it's behaviour across project types.

Sorry I can't be of more help. I'm not 100% familiar with the intricacies of how this works.

**Comment by justscribe** [comment]
I think it's enough info to other people to solve a similar problem.
Thank you for help.

**Comment by OneFingerCodingWarrior** [comment]
i have the same problem,
with a .NET console app, which reference the MonoTorrent library,
after add dependency of reusabletasks to the console app, the issue fixed
