### ISSUE TITLE
Files blocking

### ISSUE THREAD

**Issue by justscribe** [mono/monotorrent#190]
Hi,

I'm ivestigted one issue, when I've stopped the TorrentManager, the files in this torrent (sparsed or not fully downloaded) is still locked and can't be deleted.

**Comment by alanmcgovern** [comment]
I wonder if there's a subtle race here and pieces which have been received are still being synchronously processed after StopAsync has closed the filestreams, which causes the files to be re-opened. 

I'll do some checking to ensure all PeerMessage handling is cancelled after the mode changes to Stopping or Stopped

**Comment by justscribe** [comment]
Can I check somehow now, that Monotorrent is blocking files?
**Engine.DiskManager.PendingWrites** or **Engine.DiskManager.PendingReads** shows nothing(

**Comment by alanmcgovern** [comment]
I have a patch locally to ensure the DiskManager does not reopen streams after the torrent has been stopped. Currently it's possible that messages which are handled asynchronously will execute after the CloseStreams method is invoked, which will cause the filestreams to reopened. There's no public way to access this part of the library as it should just work.

There's no reliable way to enforce the streams are closed. One way you could try would be to save the fast resume data, call HashCheckAsync then StopAsync, then reload the fast resume data. It's a bit of a hack but may solve the problem if you need a workaround now.

**Comment by justscribe** [comment]
If I understood correctly, the steps you're adviced is:
1. StopAsync.
2. Save fast resume.
3. HashCheckAsync.
4. StopAsync.
5. Load fast resume.
If so, unfortunately It's not working.

**Comment by justscribe** [comment]
Temporary solution:
Make DiskManager.CloseFilesAsync public.
Make PeerManager.ClearAll public.
On Stop :
1. PeerManager.ClearAll
2. Unregister TorrentManager.
3. DiskManager.CloseFilesAsync.

**Comment by alanmcgovern** [comment]
I think this should be addressed by https://github.com/mono/monotorrent/tree/diskmanager-disposing . Could you give that branch a try and see if it solves the problem for your case?

**Comment by justscribe** [comment]
The problem is solved, thank you a lot.

**Comment by alanmcgovern** [comment]
Awesome! I'm going to test this a little more before merging it, so any feedback over the next day or two about the changes would be great! The only thing it should really affect would be code which changes the current mode (paused, hashing, stopped, etc).

Thanks for the quick reply!
