### ISSUE TITLE
How to get rid of debug message when include monotorrent project

### ISSUE THREAD

**Issue by uponatime2019** [mono/monotorrent#198]
![image](https://user-images.githubusercontent.com/15900671/70864158-14006080-1f82-11ea-95e7-f7d8c648d4f2.png)
It's fine when I include from NuGet package, but when clone source and reference project, these debug messages come to Ouput window. How to remove these messages?

**Comment by alanmcgovern** [comment]
I think that's a feature of Visual Studio. I'm not sure if there's an option to disable that, but I'd look in the settings and see if there's anything about thrown exceptions being logged

**Comment by alanmcgovern** [comment]
The "Exception thrown:" string is not part of MonoTorrent. Based on that I can only assume that your IDE or runtime is causing this. If you're compiling in debug mode, try using Release mode instead. If you're running your application with a debugger attached, try running it without the debugger. If you're using 3rd party logging frameworks check if they are causing this. 

If you still have issues please feel free to reopen this, however I don't think there's anything I can change in MonoTorrent to make this not occur :)

Thanks!
