### ISSUE TITLE
a multi-file magnet link does not insert torrent name as directory

### ISSUE THREAD

**Issue by jpmikkers** [mono/monotorrent#209]
This means a normal multi-file torrent will get a directory, but the equivalent multi-file magnet will put the files directly into SavePath without creating a parent directory.

I think this can be fixed in MetadataMode.cs SwitchToRegular() line 216, would you agree? I'll create a PR this weekend.

**Comment by alanmcgovern** [comment]
Yup, that looks like the perfect place to make the change.

I think the missing part is the `SavePath` is not updated as it should be. If you create a TorrentManager from a `Torrent` then savePath is set like this: https://github.com/mono/monotorrent/blob/master/src/MonoTorrent/MonoTorrent.Client/Managers/TorrentManager.cs#L303

If we update SavePath in `SwitchToRegular` then the semantics will be the same between both pieces of code.  If you have other ideas on how to better refactor that, feel free!

For bonus points - there are some tests on MetadataMode already. It would be good to verify that the various paths are correct when the metadata has been received. An extra check or two in a test like this would be wonderful! https://github.com/mono/monotorrent/blob/master/src/MonoTorrent.Tests/MonoTorrent.Client.Modes/MetadataModeTests.cs#L137-L145 . The tests currently do single file torrents ( https://github.com/mono/monotorrent/blob/master/src/MonoTorrent.Tests/MonoTorrent.Client.Modes/MetadataModeTests.cs#L57 ) but it should be reasonably easy to swap it to a multi-file one instead.
