### ISSUE TITLE
How to download only one file from large torrent

### ISSUE THREAD

**Issue by Hippey** [mono/monotorrent#21]
Hello!

How to download only one file from large torrent?

I tried this code:

string allowed = "test.exe";

Torrent torrent = Torrent.Load(TorrentFile.FullName);

 for (int i = 0; i < torrent.Files.Length; i++)
{
    if (!torrent.Files[i].Path.Contains(allowed))
    {
        torrent.Files[i].Priority = Priority.DoNotDownload;
    }
    else
    {
       torrent.Files[i].Priority = Priority.Highest;
    }
}

But with this code monotorrent whatever downloads all files.

How to fix that?

Thanks

**Comment by alanmcgovern** [comment]
It may still create partial files because that's how bittorrent works. If a piece spans the end of one file )(marked do not download) and the start of another (Which is marked download) then the do-not-download file will be created so that the hash can be verified correctly.
