### ISSUE TITLE
Sanitize torrent paths

### ISSUE THREAD

**Issue by jpmikkers** [mono/monotorrent#212]
It looks like there are no limitations on the characters you're allowed to use in the path components of a torrent (a quick scan of the BEPs also doesn't reveal any restrictions). Perhaps we should add a path sanitizer, so a .torrent could not escape the intended download path? e.g. don't allow double dots, slashes, backslashes.. probably more :) Or check if the expanded/normalized path of a torrent target file is not shorter than the expanded download path.

**Comment by alanmcgovern** [comment]
`TorrentCreator` sanitises, but it looks like `Torrent.Load` doesn't have the same kind of basic sanitisation. It should!

**Comment by alanmcgovern** [comment]
Fixed!
