### ISSUE TITLE
Access to peers

### ISSUE THREAD

**Issue by jpmikkers** [mono/monotorrent#217]
Would you consider adding readonly access to the momentary list of peers? (something that returns a clone of the internal list). I'm writing a managed clone/emulator of transmission-rpc on top of monotorrent, and that API allows requesting detailed peer information.

Maintaining my own list via the TorrentManager.Peer* events works (sort of), but looks rather clunky.

**Comment by alanmcgovern** [comment]
This API should give you what you need. https://github.com/mono/monotorrent/blob/669e84add59fad255db1202c3bb19bb7f3fff0f7/src/MonoTorrent/MonoTorrent.Client/Managers/TorrentManager.cs#L476-L480

**Comment by alanmcgovern** [comment]
If you have any issues with that let me know :) Thanks!

(I would've closed the issue earlier but i had temporary admin issues with the repo. Hopefully it's solved now ;p )

**Comment by jpmikkers** [comment]
Doh! I overlooked that one. Thanks!

**Comment by alanmcgovern** [comment]
No problem!
