### ISSUE TITLE
SOCKs and NAT-traversal

### ISSUE THREAD

**Issue by ghost** [mono/monotorrent#24]
Any plans to support SOCKS and NAT-traversal in future release?

**Comment by freshstudio** [comment]
@aaronsace Implement NAT traversal on your own. It's not that hard I believe.

> making it close to useless...
No, it still can be used in a torrent client and it works very well. Your computer does not have to be reachable.

**Comment by aaronsace** [comment]
@freshstudio I've been at it for a few weeks and got MonoTorrent working very well now on my machine but I'm having problems without port forwarding. The users won't have a clue about how to forward ports so I'm hoping to get this final problem fixed. 

The DHT works and the torrent manager gets peers, but the peers slowly disappear without any connections being opened. Soon as I forward the ports, all the connections come flooding in and it starts downloading. 

So confusing, it just doesn't seem to work for me unless I forward the ports. I'm simply passing a magnet link without any trackers; does it work for you if you just pass a hash? 

I'll see if I can find any code for 'NAT traversal' after work; hopefully, if I get it working, I'll do another pull request.

**Comment by aaronsace** [comment]
https://github.com/mono/monotorrent/pull/79

**Comment by alanmcgovern** [comment]
If the port the engine is listening on is not publicly reachable, you can create *outgoing* connections but cannot accept *incoming* connections.

I'd recommend using https://github.com/mono/Mono.Nat if you want to have automatic port forwarding for upnp or nat-pmp devices.
