### ISSUE TITLE
Main directory is not visible in Torrent.Files

### ISSUE THREAD

**Issue by gjuchault** [mono/monotorrent#29]
Hi.
If you have a .torrent with some files in a directory, something like that :
- Directory1
  - File1
  - File2
  - Directory2
    - File3
  - Directory3
    - File4

Torrent.Files will look like this :
File1
File2
Directory2/File3
Directory3/File4

On torrenteditor, i can't see it too, but i have a meta-data called "Directory".
Can you do something about it ?

**Comment by alanmcgovern** [comment]
Can you include a torrent which shows the issue?
