### ISSUE TITLE
Client download speed

### ISSUE THREAD

**Issue by caracostea** [mono/monotorrent#38]
I'm experiencing some issues regarding the download speed when using the Monotorrent client engine.
I have set up a monotorrent based tracker, two clients and a torrent, with the following results:

1) Monotorrent client -> uTorrent client: download speed ~80 KB/s
2) uTorrent client -> uTorrent client: download speed ~500 KB/s

Same tracker, computers, torrent file, internet connections. Only difference is using Monotorrent client at one end.

I'm really stuck here. Any help would be appreciated.

**Comment by ashkansiroos** [comment]
Hi guys,
It is awesome to see some people successfully used this code. could you please help me?
It can not connect to the trackers even though my firewall is off. 
I really appreciate your help

**Comment by caracostea** [comment]
ashkansiroos, u cannot connect from the monotorrent client to other trackers or from other clients to the monotorrent tracker?

**Comment by ashkansiroos** [comment]
Dear caracostea,
I cannot connect the monotorrent client to trackers. I am using win 8.1 and as I mentioned, my firewall is off. 
I have this error:
Tracker did not respond to the connect requests.

This is the torrent that seems to have many seeds and peers and it also had 10 trackers.
http://torcache.net/torrent/17321655F767B524F8996ED617BA182E36B4AE40/[kickass.so]the.hobbit.2014.battle.of.the.five.armies.dvdscr.xvid.ac3.hq.hive.cm8.torrent

It is really odd :(

**Comment by caracostea** [comment]
Well, it's hard to say what it could be unless you show some code.

**Comment by ashkansiroos** [comment]
I am using the sample client in the code. Set the listening port to 6969 and run the client with the torrent file that I mentioned before.
I did not write any codes :(

**Comment by caracostea** [comment]
See if this helps:
http://monotorrent.fr.yuku.com/topic/501/Adding-the-useragent#.VK_WtSuUd8F

**Comment by caracostea** [comment]
Well, looks like the current version already has this fix implemented. See if you are using the latest version first.

**Comment by ashkansiroos** [comment]
I have the last version. I have downloaded the source 1 week ago and I have  the mentioned code as they said.
request.UserAgent = MonoTorrent.Common.VersionInfo.ClientVersion; 
Also, I have problems to connect all trackers, not only the private ones :(

**Comment by caracostea** [comment]
Can you connect to those trackers using other torrent clients?

**Comment by alanmcgovern** [comment]
Someone could implement UTP pretty easily if they wanted.

Other than that, TCP is pretty fast :p
