### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by CoenraadS** [mono/monotorrent#43]
http://www.monotorrent.com/ doesn't seem to work anymore.

Last commit was in 2013.

**Comment by hhowe29** [comment]
It appears that Alan has moved on to bigger things. Perhaps the torch could be passed to a new maintainer, or the main repo could be opened to a group of maintainers? I am not github savvy enough to know how that works. 

The monotorrent code is too cool to let the project wither, but it needs more work, as evidenced by the commit history of forked projects.

**Comment by samhocevar** [comment]
I am going to try and revive the project. For now I mostly plan on merging/closing pull requests, triaging bugs, then find out which forks are actively maintained and try to combine efforts.
