### ISSUE TITLE
I can not download any file

### ISSUE THREAD

**Issue by ashkansiroos** [mono/monotorrent#44]
Hi,
Could anyone please help me?
I am using win 8.1 and I have turned of my firewall. I tried to download many files like the one below but monotorrent could not connect to any tracker.
the file has 10 trackers and is very popular. I am using the sample client existing in the project. 

Thanks a lot

http://torcache.net/torrent/17321655F767B524F8996ED617BA182E36B4AE40/[kickass.so]the.hobbit.2014.battle.of.the.five.armies.dvdscr.xvid.ac3.hq.hive.cm8.torrent

**Comment by bbougot** [comment]
Same thing here, stucked on the System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host at System.Net.Sockets.Socket.

**Comment by samhocevar** [comment]
I am going to assume you just had a firewall configuration problem and I will close this issue, because it’s very old. If you are still having trouble, feel free to reopen it and please add a link to a new torrent, because the above one has since expired.
