### ISSUE TITLE
There is an problem whit BigInteger class

### ISSUE THREAD

**Issue by toplevmas** [mono/monotorrent#45]
In MonoTorrent.Dht project,the NodeId class has a method below:

```
 internal BEncodedString BencodedString()
{
       return new BEncodedString(value.GetBytes());
}
```

The method convert BigInteger num to bytes, the `BigInteger .GetBytes` return a dynamic length bytes,
sometime the length less than 20.  but in dht , it shoud be a 20 length value 
 original `BigInteger .GetBytes`:

```
 public byte[] GetBytes()
        {
            if (this == 0) return new byte[1];

            int numBits = BitCount();
            int numBytes = numBits >> 3;
            if ((numBits & 0x7) != 0)
                numBytes++;

            byte[] result = new byte[numBytes]; //here is a dynamic length
```

I modify the  `BigInteger .GetBytes`  mothed like this:

```
 public byte[] GetBytes()
        {
            if (this == 0) return new byte[1];

            int numBits = BitCount();
            int numBytes = numBits >> 3;
            if ((numBits & 0x7) != 0)
                numBytes++;

            byte[] result = new byte[20];
```

**Comment by alanmcgovern** [comment]
I solved it another way - the NodeID class already stores the initial byte[], so we can just change the impl to `return new BEncodedString(bytes);`
