### ISSUE TITLE
Error in link on github

### ISSUE THREAD

**Issue by lilleindi** [mono/monotorrent#50]
Hi
When clicking the link here it redirects to a wrong site
![skaermbillede 2016-07-26 kl 00 12 39](https://cloud.githubusercontent.com/assets/19615773/17119385/d3f82d38-52c5-11e6-8cdb-16c87b41dc6c.png)

Regards
Jakob

**Comment by shersh** [comment]
It's because domain name hosting is over. Like this project. 
Last commit was 3 years ago =)

**Comment by ioanb7** [comment]
So is it still working though!

**Comment by ioanb7** [comment]
?

**Comment by Mga-Denmark** [comment]
It's still working, but i'm unsure if its maintained like it used to.

**Comment by samhocevar** [comment]
I am going to help maintain the project, we’ll see how it goes. I removed the link for now.
