### ISSUE TITLE
Finding the new Docs

### ISSUE THREAD

**Issue by chez14** [mono/monotorrent#59]
Hi guys, I've been struggling finding any other Torrent lib for my project, and this one is the best option available.

I'm wondering where's the newest documentation of the site, [this](http://www.mono-project.com/archived/monotorrent/) one is quite old, since the difference is almost 8 years-ish been left.

Thanks!

**Comment by alanmcgovern** [comment]
Things haven't  changed, so those docs are up to date!

The sample client is best.
