### ISSUE TITLE
Stuck downloading on last pieces

### ISSUE THREAD

**Issue by Ilyatk** [mono/monotorrent#6]
I have problem if most of all seed send bad pieces. It's not important why. For example, i have 10 bad seeds and 2 good(weebseeds). On last 1-3 pieces i can't finish downloading because alwayse got hash failed.
In PieceManager in function PieceDataReceived i changed this:
                                    if (peers [i].Peer.TotalHashFails == 5)
                                        peers[i].ConnectionManager.CleanupSocket (id, "Too many hash fails");
to 
                                    if (peers[i].Peer.TotalHashFails >= 5)
                                         peers[i].ConnectionManager.CleanupSocket(peers[i], "Too many hash fails");  
Now i don't have peers with more than 8 hash fail(8 is still possible). So after few minutes I have only WebSeeds. Yeah I changed DownloadLogic in Mode.cs to have WebSeed always. But I still have problem. 
Webseeds can stuck and I don't get any response from them.

It will be good if monotorrent switch to webseed more quickly and finish downloading. Can anybody help me?

**Comment by alanmcgovern** [comment]
It should download correctly to begin with. It should work now?
