### ISSUE TITLE
Local Peer Discovery not working with multiple network interfaces

### ISSUE THREAD

**Issue by Dwarfmeat** [mono/monotorrent#60]
Bug:
Local Peer Discovery only works on the default network interface, the multicast packet is not send to other interfaces. (e.g. you have a wlan&lan adapter only one will it work). Especially a problem with virtual nics.

Fix:
Iterate all nics capable of multicast and send a multicast packet for each one.
This change worked for me (not really 'clean', mostly based on https://stackoverflow.com/a/14603966 ):
https://github.com/Dwarfmeat/monotorrent/blob/master/src/MonoTorrent/MonoTorrent.Client/Managers/LocalPeerManager.cs

**Comment by alanmcgovern** [comment]
Seems fine! Can you submit a pull request?
