### ISSUE TITLE
Why i couldn't download any .torrent file?

### ISSUE THREAD

**Issue by stuboy9** [mono/monotorrent#61]
when i try to download .torrent file with sampleClient, it always tell me "Tracker did not respond to the connect requests" or "the tracker could not be contracted",but the same file could be downloaded with qbittorrent.anyone knows what happend?

**Comment by freshstudio** [comment]
Is the tracker a UDP one?

W dniu poniedziałek, 28 maja 2018 stuboy9 <notifications@github.com>
napisał(a):
> when i try to download .torrent file with simpleClient, it always tell me
"Tracker did not respond to the connect requests",but the same file could
be downloaded with qbittorrent.anyone knows what happend?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci6.googleusercontent.com/proxy/t6XsYbkvS4v44pB5WJgJ_t92wYMT5Vz6kn7PMD6nx1juz-Jbo60pn2AOAid313A0uF4a87krpU8H0-WZDNVV-CzAImig3-sF5-WDYGhm_joq77hxb52Hw3AKOEe1HJ8wPSVe5XXlj3FuCeMhilCiR8hCs_18hA=s0-d-e1-ft#https://github.com/notifications/beacon/AL3zCvSv5cSnbkgUqHFN84W5nydW9yUoks5t22SUgaJpZM4UPjhF.gif>

**Comment by stuboy9** [comment]
http trackers get the same issuses.But some http trackers can get peers,but the download speed is almost 0kb/s.udp trackers can't  be downloaded at all.

**Comment by f5inet** [comment]
Surely the tracker bans the user agent sended by monotorrent. Clone the
user agent of qbittorrent, for example.

Also, make sure that the tracker is sending you peers.

2018-05-29 5:19 GMT+02:00 stuboy9 <notifications@github.com>:

**Comment by stuboy9** [comment]
I replaced “MO1000” with "qB4110", but still can't connect the tracker.

**Comment by anzer987** [comment]
i would like to write torrent client on wpf using monotorrent, but the same error, almost all of the torrent files never work out. (Test on your sample client)

**Comment by stuboy9** [comment]
TorrentManager.cs -> Start() -> `if (TrackerManager.CurrentTracker != null)
                {
                    if (this.trackerManager.CurrentTracker.CanScrape)
                        this.TrackerManager.Scrape();
                    //this.trackerManager.Announce(TorrentEvent.Started); // Tell server we're starting
                    this.trackerManager.NewAnnounce(TorrentEvent.Started);
                }`
it used `//this.trackerManager.Announce(TorrentEvent.Started); // Tell server we're starting`
and you can find in Announce(), mono client send request for tracker after get last response.
so, if a request need a long time for response,it looks like dosen't work.

**Comment by alanmcgovern** [comment]
If the trackers are offline, then you should try to use DHT to locate peers.
