### ISSUE TITLE
is possible Download mode without Hashing check not using FastResume

### ISSUE THREAD

**Issue by yunchiri** [mono/monotorrent#88]
if  app running on  seeder-computer

manager.start() <--
is possible start as seeding mode without Hashing check  not using FastResume

**Comment by alanmcgovern** [comment]
Nope!

If you have partial (or full) data downloaded already, then the engine needs to be able to find a fast resume file containing the results of a previous HashCheck, or you need to run a HashCheck. You can hack the code to not do this, but then if you have incomplete/corrupt data you will send other people bad data.
