### ISSUE TITLE
is ChangePicker function correct?

### ISSUE THREAD

**Issue by yunchiri** [mono/monotorrent#90]
https://github.com/mono/monotorrent/blob/774a12494006acd21c117d36a9303732ac509139/src/MonoTorrent/MonoTorrent.Client/Managers/PieceManager.cs

line 218,219 

        internal void ChangePicker(PiecePicker picker, BitField bitfield, TorrentFile[] files)
        {
            if (unhashedPieces.Length != bitfield.Length)
                unhashedPieces = new BitField(bitfield.Length);

            picker = new IgnoringPicker(bitfield, picker); <----
            picker = new IgnoringPicker(unhashedPieces, picker); <----
         
            IEnumerable<Piece> pieces = Picker == null ? new List<Piece>() : Picker.ExportActiveRequests();
            picker.Initialise(bitfield, files, pieces);
            this.picker = picker;
        }
`

picker is always  **picker = new IgnoringPicker(unhashedPieces, picker);**?

**Comment by alanmcgovern** [comment]
The code you marked is the equivalent of:

```
        picker = new IgnoringPicker(unhashedPieces, new IgnoringPicker(bitfield, picker));
```
I think it's ok?
