### ISSUE TITLE
Download Piece

### ISSUE THREAD

**Issue by cores-system** [mono/monotorrent#95]
Hello, how do I download a separate piece ?

```
Torrent torrent = Torrent.Load("file.torrent");
byte[] array = DownloadPiece(torrent.Files[0].StartPieceIndex));

byte[] DownloadPiece(int index)
{
   // 
}
```

**Comment by alanmcgovern** [comment]
You'd have to write a custom PiecePicker for this kind of logic.

In short, you'd have to create a PiecePicker which returns false ( https://github.com/mono/monotorrent/blob/master/src/MonoTorrent/MonoTorrent.Client/PiecePicking/PiecePicker.cs#L92-L96 ) if a peer *does not* have the piece you want.

Then you should override the PickPiece https://github.com/mono/monotorrent/blob/master/src/MonoTorrent/MonoTorrent.Client/PiecePicking/PiecePicker.cs#L106-L110 method to do something like:

```
        public virtual MessageBundle PickPiece(PeerId id, BitField peerBitfield, List<PeerId> otherPeers, int count, int startIndex, int endIndex)
        {
            CheckOverriden();
            var bitfield = peerBitfield.Clone ().SetAll (false);
            bitfield.SetTrue (pieceIndex);
            return picker.PickPiece(id, bitfield, otherPeers, count, startIndex, endIndex);
        }
```
