### ISSUE TITLE
engine stuck

### ISSUE THREAD

**Issue by OneFingerCodingWarrior** [mono/monotorrent#96]
Hi:

ConnectionManager.cs

1、if you delete one torrent mission, then the engine stuck
2、engine will stuck forever if one torrent file has no available peers even other torrent manager with many available peers

internal void TryConnect()
        {
            int lastConnect = TryConnectIndex < engine.Torrents.Count ? TryConnectIndex : 0;//1
            bool connected = true;
            Int32 nRound = 0;

            // If we have already reached our max connections globally, don't try to connect to a new peer
            while (OpenConnections < this.MaxOpenConnections && PendingConnects.Count < this.MaxHalfOpenConnections && connected)
            {
                nRound = 0;
                connected = false;
                // Check each torrent manager in turn to see if they have any peers we want to connect to
                for (int i = lastConnect; i < engine.Torrents.Count; ++i)
                {
                    if (TryConnect(engine.Torrents[i]))
                    {
                        connected = true;
                        TryConnectIndex = (i + 1) % engine.Torrents.Count;
                    }
                    else//only if all the torrents connection failed, we can break the loop//2
                    {
                        ++nRound;
                        connected = nRound != engine.Torrents.Count;
                    }
                }

                lastConnect = 0;
            }
        }

**Comment by alanmcgovern** [comment]
Thanks for the issue and proposed patch! I went with a slightly different approach, which should be a bit less code and a little clearer to read. Let me know if this addresses the issue you encountered! I believe the new approach will be a fairer way to connect to peers when there are multiple active downloads :)
